name: xeus-kernels
channels:
  - https://prefix.dev/emscripten-forge-4x
  - https://prefix.dev/conda-forge
dependencies:
  - xeus-python
  - xeus-lua
  - xeus-cpp
  - numpy
  - matplotlib
  - pillow
  - ipywidgets
  - cockle
  - terminal-external-command
  - pip:
      - ipycanvas
