name: Build and Deploy

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install micromamba and build environment
        uses: mamba-org/setup-micromamba@v3
     #   with:
     #     micromamba-version: '1.5.8-0'
      #    environment-file: .github/build-environment.yml
      #    cache-environment: true

      # Step 1: Build your custom xeus-cpp WASM
      - name: Build xeus-cpp WASM
        shell: bash -l {0}
        run: |
          micromamba create -n blah
          micromamba activate blah
          micromamba install jupyterlite-xeus jupyter_server specta xeus-cpp
          ls
          jupyter lite build --XeusAddon.environment_file=environment.yml \
            --lite-dir=content \
            --output-dir dist 
      # --apps tree lab repl

    #  - name: Create cockle WASM environment
     #   run: |
      #    micromamba create -p ./cockle_wasm_env -y \
       #     cockle_fs coreutils grep less sed git2cpp lua nano tree vim \
        #    --platform=emscripten-wasm32 \
         #   -c https://repo.prefix.dev/emscripten-forge-4x \
          #  -c conda-forge

  #    - name: Build the JupyterLite site
  #      shell: bash -l {0}
        #run: 

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
