name: Build and Deploy

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install micromamba and build environment
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.8-0'
          environment-file: .github/build-environment.yml
          cache-environment: true

      # Step 1: Build your custom xeus-cpp WASM
      - name: Build xeus-cpp WASM
        shell: bash -l {0}
        run: |
          git clone --depth=1 https://github.com/compiler-research/xeus-cpp.git
          cd xeus-cpp
          micromamba create -f environment-wasm-build.yml -y
          micromamba activate xeus-cpp-wasm-build
          micromamba create -f environment-wasm-host.yml \
            --platform=emscripten-wasm32 \
            -c https://prefix.dev/emscripten-forge-4x \
            -c https://prefix.dev/conda-forge
          mkdir build && cd build
          export BUILD_PREFIX=$MAMBA_ROOT_PREFIX/envs/xeus-cpp-wasm-build
          export PREFIX=$MAMBA_ROOT_PREFIX/envs/xeus-cpp-wasm-host
          export SYSROOT_PATH=$BUILD_PREFIX/opt/emsdk/upstream/emscripten/cache/sysroot

          emcmake cmake \
            -DCMAKE_BUILD_TYPE=Release                        \
            -DCMAKE_INSTALL_PREFIX=$PREFIX                    \
            -DCMAKE_FIND_ROOT_PATH=$PREFIX                    \
            -DSYSROOT_PATH=$SYSROOT_PATH                      \
              ..

          # emmake make check-xeus-cpp
          emmake make install      
          export GITHUB_ENV=${{env.PREFIX}}

      - name: Create cockle WASM environment
        run: |
          micromamba create -p ./cockle_wasm_env -y \
            cockle_fs coreutils grep less sed git2cpp lua nano tree vim \
            --platform=emscripten-wasm32 \
            -c https://repo.prefix.dev/emscripten-forge-4x \
            -c conda-forge

      - name: Build the JupyterLite site
        shell: bash -l {0}
        run: |
          MY_VAR=$GITHUB_ENV
          micromamba activate build-env
          jupyter lite build \
            --XeusAddon.prefix=$MY_VAR \
            --XeusAddon.mounts="$MY_VAR/share/xeus-cpp/tagfiles:/share/xeus-cpp/tagfiles" \
            --XeusAddon.mounts="$MY_VAR/etc/xeus-cpp/tags.d:/etc/xeus-cpp/tags.d" \
            --XeusAddon.prefix=$(pwd)/cockle_wasm_env     
            --contents content --output-dir dist --apps tree --apps lab

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
